import Foundation

/// A fully populated, entirely local mailbox for the product tour. Each
/// dashboard category has three readable examples from the moment it opens.
struct OnboardingRehearsal: Sendable {
    enum Category: String, CaseIterable, Sendable {
        case attention, newsletters, calendar, shipments, banking, receipts
    }
    enum Lane: Sendable { case attention, records, reading }
    struct Message: Identifiable, Equatable, Sendable {
        let id: Int
        let sender: String
        let subject: String
        let body: String
        let explanation: String
        let category: Category
        var isRead = false
        var isDone = false
        var lane: Lane {
            switch category {
            case .attention: .attention
            case .newsletters: .reading
            default: .records
            }
        }
    }
    private(set) var messages = Self.fixtures

    mutating func reset() { self = Self() }
    mutating func open(_ id: Int) {
        guard let index = messages.firstIndex(where: { $0.id == id }) else { return }
        messages[index].isRead = true
    }
    mutating func setDone(_ id: Int, done: Bool) {
        guard let index = messages.firstIndex(where: { $0.id == id }) else { return }
        messages[index].isDone = done
    }

    private static let fixtures: [Message] = [
        Message(id: 1, sender: "Maya Chen", subject: "For your notes: the plan we agreed", body: "Hey Jamie,\n\nA quick recap so you have everything in one place. We’re going with the quieter opening, keeping the product screenshots, and moving the longer background section to the appendix.\n\nI’ve updated the shared draft to match. Please read this when you have a moment so we’re on the same page. No reply needed.\n\nThanks!\nMaya", explanation: "Maya shared the agreed plan for you to read. No reply is needed.", category: .attention),
        Message(id: 2, sender: "Corner Coffee", subject: "Your receipt · $8.50", body: "CORNER COFFEE\nPayment received\n\nOrder #CC-1042\nOat latte                         $5.00\nButter croissant                  $3.50\nTotal paid                        $8.50\n\nPaid with Visa •••• 4242\nNo signature required.\n\nThank you for visiting Corner Coffee. Please keep this receipt for your records.", explanation: "A purchase receipt. No reply or action needed.", category: .receipts),
        Message(id: 3, sender: "Cats Weekly", subject: "The box was the gift. The cat has spoken.", body: "CATS WEEKLY\nGood cats. Questionable decisions. Every Sunday.\n\nTHE BOX WAS THE GIFT\nYou bought the handwoven bed. You researched the orthopedic cushion. You read thirty-seven reviews. Miso has chosen the cardboard packaging, and would appreciate it if you respected the process.\n\nFIELD NOTES: THE SUNBEAM SHIFT\nAt 10:14, the warm square moves off the rug. At 10:15, so does the cat. We spent a week tracking this demanding schedule so you don’t have to.\n\nASK A CAT\nQ: Why knock a full glass off the table?\nA: It was up there. Now it’s down here. Please keep up.\n\nTHIS WEEK’S SMALL JOY\nA slow blink from across the room. Send one back.\n\nYou’re receiving Cats Weekly because the internet needed one more cat newsletter. Fictional practice edition.", explanation: "This week’s Cats Weekly: cardboard-box devotion, sunbeam schedules, and a very unhelpful advice column.", category: .newsletters),
        Message(id: 4, sender: "Alex Rivera", subject: "Dinner on Thursday?", body: "Would you like to join us for dinner on Thursday? Let me know and I'll book a table.\n\nAlex", explanation: "A personal invitation waiting for your reply.", category: .attention),
        Message(id: 5, sender: "ExFed", subject: "Your weekend bag is on its way", body: "EXFED\nShipment notification\n\nHi Jamie,\n\nWe have received your package from Rainforest and it is moving through the ExFed network. You can find your delivery details below.\n\nShipper: Rainforest\nOrder reference: RF-10485\nItem: Canvas weekend bag · Sand · Qty 1\nShipment status: Shipped\nEstimated delivery: {{delivery_date}}\nTracking number: PRACTICE-5\n\nDelivering to:\nJamie · 148 Willow Lane\nPortland, OR 97205\n\nTracking may take up to 24 hours to show movement. If your order arrives in separate boxes, we will email you a tracking update for each shipment.\n\nExFed Delivery Services\nThis is an automated shipment update. Please do not reply.", explanation: "A shipment update to keep for later.", category: .shipments),
        Message(id: 6, sender: "Haightssion", subject: "HAIGHTSSION — NO PHONES. LONG NIGHT.", body: "HAIGHTSSION\nPROGRAM 041 / AFTER DARK\n\nNO PHONES. LONG NIGHT.\nConcrete. Low light. A room built around the sound. Our next all-night session moves from stripped percussion into the slow, heavy end of morning.\n\nSATURDAY / DOORS 23:00 / UNTIL LATE\nMAIN FLOOR\n23:00 — NERA / hypnotic opening set\n02:00 — ECHO NULL / live hardware\n05:00 — SABLE FORM / closing stretch\n\nROOM TWO\nAn intimate listening room. Dub, broken rhythms, and somewhere to catch your breath.\n\nCOME AS YOU ARE\nRespect the room. Ask before touching. Leave your camera in your pocket. If something feels wrong, speak to the door team or anyone wearing a green band.\n\nDoor sales only. Entry subject to capacity. Fictional event announcement for the practice inbox.", explanation: "Haightssion announces an all-night techno session, live hardware set, and second-room listening program.", category: .newsletters),
        Message(id: 8, sender: "Corner Coffee", subject: "Your receipt · $4.75", body: "CORNER COFFEE\nYour digital receipt\n\nOrder #CC-1086\nFlat white                         $4.75\nTotal paid                         $4.75\n\nPayment method: Visa •••• 4242\nTransaction: CC-1086-APPROVED\n\nThanks for stopping by. This is your receipt; no reply is needed.", explanation: "Another receipt, filed without asking for your time.", category: .receipts),
        Message(id: 9, sender: "Harbor Bank", subject: "Your monthly statement is ready", body: "HARBOR BANK\nYour monthly statement is available\n\nHello Jamie,\n\nYour latest checking account statement is ready to view in Online Banking.\n\nAccount: Everyday Checking •••• 2048\nClosing balance: $1,240.50\nDelivery preference: Paperless\n\nTo view or download your statement, sign in to Online Banking and select Documents & Statements.\n\nWe will never ask for your password, PIN, or one-time code by email. If you did not request paperless statements, contact the number on the back of your card.\n\nHarbor Bank\nPlease do not reply to this automated notification.", explanation: "A monthly bank statement. No action needed.", category: .banking),
        Message(id: 10, sender: "Juniper Table", subject: "Your dinner reservation is confirmed", body: "JUNIPER TABLE\nYour reservation is confirmed\n\nJamie, we look forward to welcoming you.\n\nDate and time: {{event_time}}\nParty size: 3 guests\nConfirmation: JT-60218\nLocation: 214 Alder Street, Portland\n\nWe will hold your table for 15 minutes. Please let the restaurant know if your plans change or if anyone in your party has a food allergy.\n\nThank you for reserving with Juniper Table.", explanation: "A confirmed dinner reservation for tomorrow.", category: .calendar),
        Message(id: 11, sender: "Brightly", subject: "An update to our terms of service", body: "BRIGHTLY\nAn update to our Terms of Service\nEffective {{terms_date}}\n\nHi Jamie,\n\nWe’re updating our Terms of Service to make it clearer how your Brightly account and subscription work. The updated terms take effect on {{terms_date}}.\n\nHere’s what’s changing\n• Subscription renewals: We’ve clarified when a subscription renews, how billing dates are calculated, and where to manage your plan.\n• Account controls: We’ve added more detail about exporting your content, closing an account, and what happens to your data afterward.\n• Service updates: We’ve explained how we communicate changes to Brightly and where to find support if something goes wrong.\n\nWhat you need to do\nNothing. These updates do not change your current price or plan. By continuing to use Brightly after the effective date, you agree to the updated terms. You can review the full Terms of Service in Settings > Legal at any time.\n\nThanks for making room for Brightly.\nThe Brightly team\n\nYou’re receiving this required service notice because you have a Brightly account. Legal and account notices are sent even if you’ve opted out of marketing emails, and you cannot unsubscribe from these notices. Please do not reply to this automated message.\n\nBrightly, Inc. · 240 Sunbeam Avenue · San Francisco, CA 94103\nFictional company and terms, created for the Passband guide.", explanation: "Brightly shared a terms-of-service update. You can decide whether these updates deserve your attention.", category: .attention),
        Message(id: 12, sender: "The Federal Overstatement", subject: "Congress forms bipartisan committee to locate previous committee", body: "THE FEDERAL OVERSTATEMENT\nAn independent newspaper of entirely invented American politics.\n\nCONGRESS FORMS BIPARTISAN COMMITTEE TO LOCATE PREVIOUS COMMITTEE\nWASHINGTON — In a rare display of unity, lawmakers approved a new commission to determine which room the old commission was meeting in. Its first act was to request a larger room.\n\nWHITE HOUSE UNVEILS STRATEGIC RESERVE OF STRONGLY WORDED STATEMENTS\nOfficials assured the public that supplies remain adequate for six consecutive news cycles, provided no one uses “deeply” more than twice per paragraph.\n\nNATION’S INFRASTRUCTURE NOW 40% CEREMONIAL SCISSORS\nA new report praised the country’s readiness to open things while raising questions about whether the things themselves had been built.\n\nEDITORIAL: AT LAST, A FIVE-YEAR PLAN FOR NEXT WEEK\nThe plan’s authors described its first milestone as “scheduling the meeting about the milestones.”\n\nSATIRE. Every story above is fictional. No actual officials or current events are depicted. Practice edition.", explanation: "A satirical politics digest: missing committees, strategic statement reserves, and an oversupply of ceremonial scissors.", category: .newsletters),
        Message(id: 13, sender: "Rainforest", subject: "Your notebooks are out for delivery", body: "RAINFOREST\nYour package is out for delivery\n\nHi Jamie,\n\nYour order is on the delivery vehicle and should arrive today.\n\nOrder: RF-38109\nItem: Linen notebook set · 3 notebooks\nStatus: Out for delivery\nTracking number: PRACTICE-13\nDelivering to: Jamie · Portland, OR 97205\n\nNo signature is required. If you are not home, the carrier may leave your package in a safe place.\n\nWe will send one more email once delivery is complete.\nRainforest Customer Support", explanation: "A delivery update for your notebooks.", category: .shipments),
        Message(id: 14, sender: "Rainforest", subject: "Your herb planter has shipped", body: "RAINFOREST\nShipment confirmation\n\nYour order has shipped, Jamie.\n\nOrder number: RF-72841\nItem: Windowsill herb planter · Sage\nQuantity: 1\nEstimated delivery: {{delivery_date}}\nTracking number: PRACTICE-14\n\nYour package includes the planter, a drainage tray, and a care guide. Please check the contents when it arrives and keep the packaging until you are happy with your order.\n\nQuestions about your delivery? Contact our care team with your order number.\nRainforest", explanation: "A shipment update for your herb planter.", category: .shipments),
        Message(id: 15, sender: "Cedar Credit", subject: "Your automatic payment is scheduled", body: "CEDAR CREDIT\nYour AutoPay payment is scheduled\n\nJamie, your upcoming payment is all set.\n\nCard account: Cedar Rewards •••• 5310\nPayment amount: $86.20\nPayment date: {{payment_date}}\nPayment method: Linked checking account\nConfirmation number: AP-593108\n\nNo action is needed. Please make sure your payment account has sufficient funds on the scheduled date.\n\nTo review or change this payment, sign in and open Payments > Scheduled payments.\n\nThis is a service notification about your account, not a promotional email.\nCedar Credit Card Services", explanation: "An automatic card payment is already scheduled.", category: .banking),
        Message(id: 16, sender: "Harbor Savings", subject: "Your savings transfer is complete", body: "HARBOR SAVINGS\nYour transfer is complete\n\nHello Jamie,\n\nThe following transfer has been completed successfully.\n\nAmount: $250.00\nFrom: Everyday Checking •••• 2048\nTo: Harbor Savings •••• 7712\nStatus: Complete\nReference number: TR-087241\n\nThe funds are now available in your savings account. You can review this transaction in your account activity.\n\nIf you do not recognize this transfer, contact us using the number shown in your banking app.\n\nHarbor Savings\nThis mailbox is not monitored.", explanation: "A completed transfer to your savings account.", category: .banking),
        Message(id: 17, sender: "Zip", subject: "Invitation: Design review with Maya", body: "Maya Chen is inviting you to a scheduled Zip meeting.\n\nTopic: Design review with Maya\nWhen: {{event_time}}\nDuration: 30 minutes\nOrganizer: Maya Chen\nGuests: Jamie, Alex Rivera\n\nJoin Zip Meeting\nhttps://zip.example/j/82451073926\n\nMeeting ID: 824 5107 3926\nPasscode: design\n\nAgenda\n1. Walk through the first draft\n2. Share feedback on the opening\n3. Agree on next steps\n\nPlease bring any notes you would like to discuss.\n\nThis invitation contains a fictional meeting for the practice inbox.", explanation: "Maya invited you to a 30-minute design review on Zip.", category: .calendar),
        Message(id: 18, sender: "City Library", subject: "Your author evening reservation", body: "CITY LIBRARY\nYour event registration is confirmed\n\nThank you for registering, Jamie.\n\nEvent: An evening with Nora Vale · The Atlas of Small Things\nDate and time: {{event_time}}\nVenue: City Library · Main Hall\nSeats reserved: 1 · Free community event\nProgram: A reading, conversation, audience questions, and book signing.\nAccessibility: Step-free access to the Main Hall.\nRegistration number: CL-49371\n\nDoors open 30 minutes before the event. Please show this confirmation at the entrance; printing is not necessary. Seating is unassigned.\n\nIf you can no longer attend, please let our events team know so we can offer your place to someone on the waiting list.\n\nCity Library Events", explanation: "An author evening reservation to keep on your calendar.", category: .calendar),
        Message(id: 19, sender: "Maple Books", subject: "Your receipt · $24.00", body: "MAPLE BOOKS\nThank you for your purchase\n\nReceipt #MB-20491\nPaperback                          $24.00\nTotal paid                         $24.00\n\nPaid with Visa •••• 4242\nItems purchased: 1\n\nPlease retain this receipt. Unused items may be returned with proof of purchase under our store return policy.\n\nMaple Books\nA good book is time well spent.", explanation: "A book purchase receipt. No action needed.", category: .receipts),
    ]
}
